### ISSUE TITLE
Invisible buff not working

### ISSUE THREAD

**Issue by fredso104** [pryans/kcd-cheat#35]
All other cheats are working perfectly, but the invisibility cheat has not worked since I downloaded the mod - I’m playing the monastery quest and I keep getting caught trespassing despite constantly turning on the buff though commands. The console always tells me that the buff has been added every time I put the command in but it doesn’t actually work in game.

**Comment by pryans** [comment]
This command was changed a while ago by @wilecoyote and I'm unsure what it does or if it works.
https://github.com/pryans/kcd-cheat/commit/fc4c03a46d7b6216565223990adb479ebc3a7728

It looks like it adjusts some params as follows:
params="evi-300,lpv-300,con-300,noi-300"

Since this is changing the buff database table it could be the case that another mod you have is also changing the same table and this change is lost in the process.
https://github.com/pryans/kcd-cheat/commit/fc4c03a46d7b6216565223990adb479ebc3a7728#diff-3e7a9a4210f86c6738c30d6e8b9b7f7158a62caaec3bc9788a38c62f3a02ec5b

You could try disabling other mods or put cheat last in your load order.

**Comment by fredso104** [comment]
Unfortunately I’ve tried both removing other mods and also putting this one at the bottom of the load order - still no luck, I got seen pickpocketing for both attempts.

**Comment by wilecoyote** [comment]
I didn't change the buff, I just took it from Lernos (see image below) after testing the change and talking to Lernos about it.
![image](https://user-images.githubusercontent.com/1034673/217696312-7f846376-053b-4ded-9d48-7dd4d4e1c82d.png)

As far as i can tell the invisibility command works exactly as it should. Henry does not actually become invisible. Only the visibility, conspicuousness and noise values are set to 0, which works fine in version 1.50 of the mod.

![KingdomCome 2023-02-09 02-16-11](https://user-images.githubusercontent.com/1034673/217690496-9f99c057-ceda-4bc3-b195-4c12a085286c.png)

Maybe it would work better if you set: **params="vib-300,con-300,noi-300"**
![image](https://user-images.githubusercontent.com/1034673/217693018-9c736dc8-6662-4b7c-9e55-f41ffd1beb10.png)
![image](https://user-images.githubusercontent.com/1034673/217693216-62ebc922-3bcc-4e43-a483-dd195ab7fa94.png)
![image](https://user-images.githubusercontent.com/1034673/217693319-794b2b5f-de5a-4130-8213-44848fd3d708.png)

**EDIT:** I did a little bit of testing it seems that the derived stat **vib** is not working correctly. That's why Lernos splitted it. I've changed the buff to: **params="con-300,evi-300,lpv-300,noi-300,ors-10"** on my pc and it worked well. Also during daylight.

![image](https://user-images.githubusercontent.com/1034673/217709854-6f558ac9-e1e9-4f53-a5e8-9da6c8606c6e.png)

**Comment by fredso104** [comment]
Thank you very much! Changing the ors was very effective, it’s much easier now. I also must have misunderstood that the invisibility buff doesn’t actually make you invisible to everyone, just less easier to notice so I’m very sorry for this inconvenience, thank you so much for your support!
