### ISSUE TITLE
Review release notes

### ISSUE THREAD

**Issue by pryans** [pryans/kcd-cheat#39]
@wilecoyote can you review the release notes for 1.53, I'm assuming the buffs have new IDs and so once you upgrade you can't use the new commands to remove the old IDs making the change non-backward compatible. I've documented the upgrade process. Let me know If that isn't correct or something is off. Thanks.
https://github.com/pryans/kcd-cheat/releases/tag/1.53

**Comment by wilecoyote** [comment]
Hi, I have been using this version for weeks with an existing save game and have no problems. The buffs were defined as system buffs. Since the changes in **cheat_core_buffs.lua**  now will prevent user from using them by filtering them out on search the 
the invisibility and immortal command would not work anymore. So, i had to change them. System- and Script buffs shouldn't be used after the game has loaded. There are some small exceptions such as the savior schnapps.

EDIT: I misunderstood you. You're ofc right. If a user has the buff applied, he must remove it before he updates. However, the buffs are not saved now either. I have too often forgotten to remove them. This has simply annoyed me very much. If necessary, users can apply them via the autexec.lua at startup.

**Comment by pryans** [comment]
So the buffs aren't in the save file? That seems strange. If that's the case then the commands are backward compatible and we don't need to worry?

**Comment by wilecoyote** [comment]
As of version 1.53, they are no longer saved. Not only that it bothered me, one forgets that easily and then often can't remember what one had activated. I always read the comments a little bit to understand what mistakes are made and what can be improved.

**Comment by pryans** [comment]
Okay so starting in 1.53 the 2 buffs are transient, they do not persist across restarts of the game.

**Comment by wilecoyote** [comment]
You could also now filter out other buffs like item buffs that are not meant to be applied to the player. But I didn't want to be too restrictive. Since it affects all users and I use cheat to test my own mods and to be able to quickly debug or search for IDs which are not well documented

**Comment by pryans** [comment]
Ok thanks. I've update the release notes https://github.com/pryans/kcd-cheat/releases/tag/1.53 and I'll push this to nexus next.
